### PR TITLE
Add totalCount field to relay connection

### PR DESCRIPTION
**Pull request by kdembler**
One small change to add a `totalCount` field to relay connection object to get access of total count of queried items. This property is pretty widely used and also mentioned here: https://graphql.org/learn/pagination/#complete-connection-model

To alleviate, at the moment I need to do something like this:
```ts
const paginatedVideos = mirageGraphQLFieldResolver(obj, { first, after }, context, info)
const allVideos = mirageGraphQLFieldResolver(obj, {}, context, info)

return {
  ...paginatedVideos,
  totalCount: allVideos.edges.length,
}
```

### CODE REVIEW

**Comment by jneurock** [comment]
I'll think on this one. Since the field is not part of [the spec](https://relay.dev/graphql/connections.htm), my first feeling is to leave it out. That said, it's a tiny change and I can do a little research to see how widely used this field is. If pretty much everyone uses this, I see no reason not to add it. Thanks!

**Comment by jneurock** [comment]
I did a little digging and it seems like a popular request. There is some reasoning as to why it's not part of the official spec here: https://github.com/graphql/graphql-relay-js/pull/109#issuecomment-267734541. That said, the use case of an infinite stream seems a bit incompatible with the idea of Mirage so I think we can adopt this field.

I would ask that you add a test for this, though. Thanks again!

**Comment by jneurock** [comment]
Oh and in addition to a test, a little relevant documentation, too, if that makes sense. Not sure if we have anything about Relay pagination in the README.

**Comment by kdembler** [comment]
Seems widely used so I think it'd be nice to adopt this as you said.

Will work on adding the tests. Regarding the docs, README currently doesn't mention Relay at all so I think it could be worth to make a general issue to do that.

**Comment by kdembler** [comment]
@jneurock I've added the field to all the Relay integration tests. I didn't include it in the unit tests as it would need to test `resolveRelayConnection` directly. Let me know if you're satisfied with that or if there's anything else. :)

**Review by jneurock — APPROVED** [review]
Looks good. Thanks!

**Comment by kdembler** [comment]
@jneurock Could you maybe bump the version? I'd like to use that feature

**Comment by jneurock** [comment]
Yeah, sure, would be fine to bump the version.

**Comment by kdembler** [comment]
Thanks a lot! 🤜

**Comment by jneurock** [comment]
You're welcome. Thanks for the PR 🙂

**Pull request merged**
